# Generated by Django 4.2.4 on 2023-11-08 17:01

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('product_name',))),
                ('product_cat', models.CharField(max_length=50)),
                ('product_sub_cat', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(max_length=50)),
                ('product_disc_price', models.IntegerField(max_length=50)),
                ('product_img1', models.ImageField(upload_to='product_img')),
                ('product_img2', models.ImageField(upload_to='product_img')),
                ('product_qty', models.IntegerField()),
            ],
        ),
    ]
