# Generated by Django 4.2.4 on 2023-11-09 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Added_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('add_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('Alt_phone_number', models.IntegerField(max_length=12)),
                ('line_1', models.CharField(max_length=50)),
                ('line_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
