# Generated by Django 4.2.4 on 2023-11-09 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_cart_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
