# Generated by Django 4.2.4 on 2023-11-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
