# Generated by Django 4.2.4 on 2023-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_cart_order_id_cart_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_type',
            field=models.CharField(choices=[('online', 'online'), ('cod', 'cod')], default='cod', max_length=50),
        ),
    ]
