# Generated by Django 4.2.4 on 2023-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_delivery_status_refund_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_cat',
        ),
        migrations.AlterField(
            model_name='address',
            name='Alt_phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_disc_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
