# Generated by Django 4.2.4 on 2023-12-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_product_product_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='dashboard.category'),
            preserve_default=False,
        ),
    ]
